export const AI_TOOL_CATALOG = [
    { name: 'get_player_overview', description: 'Read a compact live overview of the player\'s Xeno, Colony, Hack Ops, Miner, and Gem Market state. The Miner section includes wallet coins; each upgrade\'s level, cap, current output, and exact next cost. For bank balances, rates, debt, or loan room, use get_bank_status. This does not mutate game state.', wikiDescription: 'View live game progress and resources.', requiresConfirmation: false, capability: null },
    { name: 'get_bank_status', description: 'Read the player\'s live bank balance, savings rate, debt rate, wallet-independent total deposited, and remaining loan room. Use this before advising on or making a bank transfer.', wikiDescription: 'Check bank savings, debt, rates, and loan room.', requiresConfirmation: false, capability: null },
    { name: 'deposit_to_bank', description: 'Move a positive amount of coins from the player\'s wallet into the bank. Deposits repay active bank debt first; any remainder becomes savings. The server checks the live wallet balance.', wikiDescription: 'Move coins from the wallet into the Bank.', requiresConfirmation: true, capability: 'bank' },
    { name: 'withdraw_from_bank', description: 'Move a positive amount of coins from the bank to the player\'s wallet. A withdrawal above available savings automatically uses remaining loan allowance and can make the bank balance negative. The server enforces all loan and debt limits.', wikiDescription: 'Move coins from the Bank to the wallet.', requiresConfirmation: true, capability: 'bank' },
    { name: 'repay_bank_debt', description: 'Repay the exact current bank debt from the player\'s wallet and return the bank balance to zero. The server settles the debt immediately before calculating the exact repayment amount.', wikiDescription: 'Repay the current Bank debt in full.', requiresConfirmation: true, capability: 'bank' },
    { name: 'collect_colony_loot', description: 'Collect all currently pending Colony loot into the player inventory.', wikiDescription: 'Collect pending Colony resources.', requiresConfirmation: true, capability: 'colony' },
    { name: 'run_colony_dailies', description: 'Collect all pending Colony loot and refill nutrition. Feeding defaults to coins unless the player explicitly requests gems.', wikiDescription: 'Collect Colony loot and refill nutrition.', requiresConfirmation: true, capability: 'colony' },
    { name: 'feed_colony', description: 'Refill Colony nutrition to its current maximum. Use coins unless the player explicitly requests gems.', wikiDescription: 'Refill Colony nutrition.', requiresConfirmation: true, capability: 'colony' },
    { name: 'sell_colony_resources', description: 'Sell Colony resources from inventory while keeping a requested quantity of each resource. Set itemTypeId to sell only one resource, or omit it to sell every resource above the keep quantity. Read the player overview first to inspect inventory and resource IDs.', wikiDescription: 'Sell Colony resources while keeping a reserve.', requiresConfirmation: true, capability: 'colony' },
    { name: 'start_colony_upgrade', description: 'Start one Colony builder upgrade: an upgrade track, the habitat level-up, or species research. Read the player overview first to compare every upgrade, its prerequisites, costs, and whether the builder is busy.', wikiDescription: 'Start a Colony track, habitat, or research upgrade.', requiresConfirmation: true, capability: 'colony' },
    { name: 'get_xeno_recipes', description: 'Read Xeno artifact crafting costs and breeding mutation recipes. Use this to plan plants for an artifact or a future breed. This never starts breeding.', wikiDescription: 'View Xeno artifact and breeding recipes.', requiresConfirmation: false, capability: null },
    { name: 'manage_xeno_garden', description: 'Harvest ready Xeno plants if requested, then plant an exact requested mix into empty grid slots and optionally fill the rest with the best available money-making plants. This never starts breeding or sells plants.', wikiDescription: 'Plant a requested Xeno garden mix.', requiresConfirmation: true, capability: 'xeno' },
    { name: 'run_xeno_dailies', description: 'Harvest ready Xeno grid slots, replant the harvested stack into empty slots, then sell surplus free plants. Retains 30 of each plant type unless the player requests a different reserve.', wikiDescription: 'Harvest, replant, and sell Xeno surplus.', requiresConfirmation: true, capability: 'xeno' },
    { name: 'run_hackops_dailies', description: 'Collect all completed Hack Ops and redeploy the same agents on the same operation templates when still valid.', wikiDescription: 'Collect and redeploy completed Hack Ops.', requiresConfirmation: true, capability: 'hack' },
    { name: 'find_best_hackops_mission', description: 'Rank the player\'s currently available Hack Ops missions using their free agents\' actual power. Returns the strongest legal squad for each mission and ranks dispatchable missions by expected base cash per hour. This does not dispatch anything.', wikiDescription: 'Find the strongest available Hack Ops mission and squad.', requiresConfirmation: false, capability: null },
    { name: 'dispatch_hackops_mission', description: 'Dispatch selected available agents on a new Hack Ops mission. Read the player overview first for available mission template IDs, agent IDs, power, and availability.', wikiDescription: 'Send selected agents on a Hack Ops mission.', requiresConfirmation: true, capability: 'hack' },
    { name: 'run_miner_dailies', description: 'Collect available Miner cash, collect whole Factory gems, and open every remaining free Miner lootbox. This never buys paid lootbox opens.', wikiDescription: 'Collect Miner rewards and free lootboxes.', requiresConfirmation: true, capability: 'miner' },
    { name: 'purchase_miner_upgrades', description: 'Purchase one or more levels of a Miner upgrade. This can spend coins or gems and stops safely at the first failed purchase. Read the player overview first so the player can be told the current level and next cost.', wikiDescription: 'Buy Miner upgrades or shop unlocks.', requiresConfirmation: true, capability: 'miner' },
    { name: 'trade_gems', description: 'Buy gems with coins or sell gems for coins on the live Gem Market. Each trade is server-authoritative and moves the market price.', wikiDescription: 'Buy or sell gems on the live market.', requiresConfirmation: true, capability: 'gems' },
    { name: 'play_casino_rounds', description: 'Legacy generic casino tool for already-pending calls. New calls use the game-specific casino tools.', wikiDescription: 'Play a bounded batch of casino rounds.', requiresConfirmation: true, capability: 'casino' },
    { name: 'play_dice_rounds', description: 'Play 1 to 200 Dice rounds. This spends coins.', wikiDescription: 'Play a bounded Dice session.', requiresConfirmation: true, capability: 'casino' },
    { name: 'play_limbo_rounds', description: 'Play 1 to 200 Limbo rounds. This spends coins.', wikiDescription: 'Play a bounded Limbo session.', requiresConfirmation: true, capability: 'casino' },
    { name: 'play_wheel_rounds', description: 'Play 1 to 200 Wheel rounds. This spends coins.', wikiDescription: 'Play a bounded Wheel session.', requiresConfirmation: true, capability: 'casino' },
    { name: 'play_magichands_rounds', description: 'Play 1 to 200 Magic Hands rounds. This spends coins.', wikiDescription: 'Play a bounded Magic Hands session.', requiresConfirmation: true, capability: 'casino' },
    { name: 'play_xenoslot_rounds', description: 'Play 1 to 200 Xeno Slot rounds. This spends coins.', wikiDescription: 'Play a bounded Xeno Slot session.', requiresConfirmation: true, capability: 'casino' },
    { name: 'play_candymadness_rounds', description: 'Play 1 to 200 Candy Madness rounds. This spends coins.', wikiDescription: 'Play a bounded Candy Madness session.', requiresConfirmation: true, capability: 'casino' },
    { name: 'play_aethergates_rounds', description: 'Play 1 to 200 Aether Gates rounds. This spends coins.', wikiDescription: 'Play a bounded Aether Gates session.', requiresConfirmation: true, capability: 'casino' },
    { name: 'play_fireinthehole_rounds', description: 'Play 1 to 200 Fire in the Hole rounds. This spends coins.', wikiDescription: 'Play a bounded Fire in the Hole session.', requiresConfirmation: true, capability: 'casino' },
    { name: 'play_bookofshadows_rounds', description: 'Play 1 to 200 Book of Shadows rounds. This spends coins.', wikiDescription: 'Play a bounded Book of Shadows session.', requiresConfirmation: true, capability: 'casino' },
    { name: 'play_spinata_rounds', description: 'Play 1 to 200 Spiñata rounds. This spends coins.', wikiDescription: 'Play a bounded Spiñata session.', requiresConfirmation: true, capability: 'casino' },
    { name: 'call_game_api', description: 'Call any authenticated Polynux game API for the current player. Use this for game actions not covered by a purpose-built tool. The exact path and payload are shown to the player for approval. Account, auth, chat, analytics, leaderboard, and AI APIs are not allowed.', wikiDescription: 'Use another allowed game action not listed above.', requiresConfirmation: true, capability: 'api' }
] as const

export const AI_TOOL_CATALOG_BY_NAME: Record<string, { description: string, wikiDescription: string, requiresConfirmation: boolean, capability: string | null }> = Object.fromEntries(
    AI_TOOL_CATALOG.map(tool => [tool.name, tool])
)
